DEPTS = [
	'Accordion',
    'Brass',
    'Choral Conducting',
    'Composition',
    'Conducting',
    'Guitar',
    'Harp',
    'Historical Performance',
    'Jazz',
    'Musical Theatre',
    'Opera',
    'Organ',
    'Piano',
    'Strings',
    'Timpani and Percussion',
    'Vocal',
    'Woodwind',
]